use_frameworks!

platform :ios, '10.0'

target 'FCPrivacyAuthTool_Example' do
  pod 'FCPrivacyAuthTool', :path => '../'

  target 'FCPrivacyAuthTool_Tests' do
    inherit! :search_paths

    
  end
end
